namespace FolioDb.Tests;

[FolioDocument]
public partial class Person
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    [FolioField("yrs")] public int? Age { get; set; }
    public Guid Key { get; set; }
    public Color Favorite { get; set; }
    public byte[]? Avatar { get; set; }
    public List<string> Tags { get; set; } = new();
    public int[] Numbers { get; set; } = [];
    public Dictionary<string, double> Metrics { get; set; } = new();
    public Address? Home { get; set; }
    public List<Address> Past { get; set; } = new();
    public DateTimeOffset Since { get; set; }
    public TimeSpan Shift { get; set; }
    public Document? Extra { get; set; }
    [FolioIgnore] public string Secret { get; set; } = "hidden";
    public string Display => $"{Name} ({Age})";
}

[FolioDocument]
public partial record Address(string Street, string City)
{
    public string? Zip { get; init; }
}

[FolioDocument]
public partial struct Point
{
    [FolioId] public ObjectId Ref { get; set; }
    public double X { get; set; }
    public double Y { get; set; }
}

public enum Color { Red, Green, Blue }

public static partial class Outer
{
    [FolioDocument]
    public partial class Nested
    {
        public string? Value { get; set; }
    }
}

public class GeneratorTests
{
    [Fact]
    public void Generated_mapper_round_trips_all_supported_member_types()
    {
        var p = new Person
        {
            Id = 7,
            Name = "Ana",
            Age = 30,
            Key = Guid.NewGuid(),
            Favorite = Color.Blue,
            Avatar = [1, 2, 3],
            Tags = ["a", "b"],
            Numbers = [3, 1, 2],
            Metrics = new() { ["h"] = 1.5 },
            Home = new Address("Rua A", "Lisboa") { Zip = "1000" },
            Past = [new Address("Rua B", "Porto")],
            Since = new DateTimeOffset(2020, 1, 1, 0, 0, 0, TimeSpan.Zero),
            Shift = TimeSpan.FromHours(8),
            Extra = Document.Parse("{ free: [1, 'form'] }"),
            Secret = "s3cr3t",
        };

        var doc = Person.ToDocument(p);
        Assert.Equal(7, doc["_id"].AsInt32);
        Assert.Equal(30, doc["yrs"].AsInt32);
        Assert.False(doc.ContainsKey("secret"));
        Assert.False(doc.ContainsKey("display"));
        Assert.Equal(2, doc["favorite"].AsInt32);

        var back = Person.FromDocument(Document.FromBytes(doc.ToBytes()));
        Assert.Equal(p.Id, back.Id);
        Assert.Equal(p.Name, back.Name);
        Assert.Equal(p.Age, back.Age);
        Assert.Equal(p.Key, back.Key);
        Assert.Equal(p.Favorite, back.Favorite);
        Assert.Equal(p.Avatar, back.Avatar);
        Assert.Equal(p.Tags, back.Tags);
        Assert.Equal(p.Numbers, back.Numbers);
        Assert.Equal(p.Metrics, back.Metrics);
        Assert.Equal(p.Home, back.Home);
        Assert.Equal(p.Past, back.Past);
        Assert.Equal(p.Since, back.Since);
        Assert.Equal(p.Shift, back.Shift);
        Assert.Equal(p.Extra.ToJson(), back.Extra!.ToJson());
        Assert.Equal("hidden", back.Secret);
    }

    [Fact]
    public void Missing_and_null_fields_use_defaults()
    {
        var back = Person.FromDocument(Document.Parse("{ _id: 1, yrs: null }"));
        Assert.Null(back.Age);
        Assert.Equal("", back.Name); // property initializer kept when field absent
        Assert.Null(back.Home);
    }

    [Fact]
    public void Struct_and_nested_types_are_supported()
    {
        var pt = new Point { X = 1, Y = 2 };
        var doc = Point.ToDocument(pt);
        Assert.False(doc.ContainsKey("_id")); // default ObjectId => generated by the database
        Assert.Equal(2.0, Point.FromDocument(doc).Y);
        Assert.Equal("x", Outer.Nested.FromDocument(Outer.Nested.ToDocument(new Outer.Nested { Value = "x" })).Value);
    }

    [Fact]
    public void Typed_collection_crud()
    {
        using var tmp = new TempDb();
        using var db = tmp.Open();
        var people = db.GetCollection<Person>("people");
        people.CreateIndex("home.city");
        people.Insert(new Person { Id = 1, Name = "Ana", Home = new Address("R", "Lisboa") });
        people.Insert(new Person { Id = 2, Name = "Bia", Home = new Address("S", "Porto") });

        Assert.Equal("Bia", people.FindOne("{ 'home.city': 'Porto' }")!.Name);
        var ana = people.FindById(1)!;
        ana.Age = 40;
        Assert.True(people.Update(ana));
        Assert.Equal(40, people.FindById(1)!.Age);
        Assert.Single(people.Find("{ yrs: { $gt: 30 } }"));

        var points = db.GetCollection<Point>("points");
        var id = points.Insert(new Point { X = 3 });
        Assert.Equal(3.0, points.FindById(id).X);
        Assert.Equal(id.AsObjectId, points.FindById(id).Ref);
    }
}
